apiVersion: v1
kind: Service
metadata:
  name: myrehab-admin
  namespace: myrehab
  labels:
    app: myrehab-admin
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: myrehab-admin
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
